export default [
  {
    files: ['assets/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        history: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        fetch: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        URL: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        speechSynthesis: 'readonly',
        NodeFilter: 'readonly',
        Node: 'readonly',
        MouseEvent: 'readonly',
        TouchEvent: 'readonly',
        matchMedia: 'readonly',
        Image: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        Date: 'readonly',
        Math: 'readonly',
        JSON: 'readonly',
        RegExp: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        Promise: 'readonly',
        Error: 'readonly',
        Intl: 'readonly',
        structuredClone: 'readonly',
        TextDecoder: 'readonly',
      },
    },
    rules: {
      'no-const-assign': 'error',
      'no-undef': 'error',
      'no-unused-vars': ['warn', { args: 'after-used', argsIgnorePattern: '^_', caughtErrors: 'none' }],
      'no-dupe-keys': 'error',
      'no-dupe-args': 'error',
      'no-duplicate-imports': 'off',
      'no-obj-calls': 'error',
      'no-func-assign': 'error',
      'no-new-func': 'error',
      'no-implied-eval': 'error',
      'no-new-wrappers': 'error',
      'no-proto': 'error',
      'no-iterator': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-unreachable': 'error',
      'no-unreachable-loop': 'warn',
      'no-useless-call': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-escape': 'warn',
      'no-invalid-regexp': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-extra-boolean-cast': 'warn',
      'no-fallthrough': 'error',
      'no-unsafe-finally': 'error',
      'default-case-last': 'warn',
      'eqeqeq': ['warn', 'smart'],
      'no-multi-str': 'warn',
      'no-redeclare': 'error',
      'no-restricted-globals': ['error', 'event'],
    },
  },
];