const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  localStorage: 'readonly',
  location: 'readonly',
  history: 'readonly',
  navigator: 'readonly',
  performance: 'readonly',
  fetch: 'readonly',
  Blob: 'readonly',
  FileReader: 'readonly',
  URL: 'readonly',
  SpeechSynthesisUtterance: 'readonly',
  speechSynthesis: 'readonly',
  NodeFilter: 'readonly',
  Node: 'readonly',
  MouseEvent: 'readonly',
  TouchEvent: 'readonly',
  matchMedia: 'readonly',
  Image: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  Date: 'readonly',
  Math: 'readonly',
  JSON: 'readonly',
  RegExp: 'readonly',
  String: 'readonly',
  Number: 'readonly',
  Boolean: 'readonly',
  Array: 'readonly',
  Object: 'readonly',
  Promise: 'readonly',
  Error: 'readonly',
  Intl: 'readonly',
  structuredClone: 'readonly',
  TextDecoder: 'readonly',
};

// Shared rules. `no-undef` is the safety net for the ES-module split: any
// shared state I forget to route through `state.*` (or function I forget to
// import) surfaces here, so a green lint == cross-module references resolve.
const rules = {
  'no-const-assign': 'error',
  'no-undef': 'error',
  'no-unused-vars': ['warn', { args: 'after-used', argsIgnorePattern: '^_', caughtErrors: 'none' }],
  'no-dupe-keys': 'error',
  'no-dupe-args': 'error',
  'no-duplicate-imports': 'off',
  'no-obj-calls': 'error',
  'no-func-assign': 'error',
  'no-new-func': 'error',
  'no-implied-eval': 'error',
  'no-new-wrappers': 'error',
  'no-proto': 'error',
  'no-iterator': 'error',
  'no-self-assign': 'error',
  'no-self-compare': 'error',
  'no-unreachable': 'error',
  'no-unreachable-loop': 'warn',
  'no-useless-call': 'warn',
  'no-useless-concat': 'warn',
  'no-useless-escape': 'warn',
  'no-invalid-regexp': 'error',
  'no-constant-condition': ['error', { checkLoops: false }],
  'no-empty': ['warn', { allowEmptyCatch: true }],
  'no-extra-boolean-cast': 'warn',
  'no-fallthrough': 'error',
  'no-unsafe-finally': 'error',
  'default-case-last': 'warn',
  'eqeqeq': ['warn', 'smart'],
  'no-multi-str': 'warn',
  'no-redeclare': 'error',
  'no-restricted-globals': ['error', 'event'],
};

export default [
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: browserGlobals,
    },
    rules,
  },
  {
    files: ['assets/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: browserGlobals,
    },
    rules,
  },
];
